var classes = [
    {
        "name": "App\\Console\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "schedule",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "commands",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Console\\Kernel",
            "Illuminate\\Console\\Scheduling\\Schedule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Console\\Kernel"
        ],
        "lcom": 2,
        "length": 6,
        "vocabulary": 6,
        "volume": 15.51,
        "difficulty": 0.5,
        "effort": 7.75,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 1,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 17,
        "loc": 30,
        "lloc": 13,
        "mi": 113.19,
        "mIwoC": 67.23,
        "commentWeight": 45.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 1.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 2.5,
        "package": "App\\Console\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Exceptions\\Handler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "report",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Exceptions\\Handler",
            "Throwable",
            "Throwable"
        ],
        "parents": [
            "Illuminate\\Foundation\\Exceptions\\Handler"
        ],
        "lcom": 2,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 1,
        "effort": 20.9,
        "level": 1,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 20.9,
        "number_operators": 1,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 27,
        "loc": 41,
        "lloc": 14,
        "mi": 113.18,
        "mIwoC": 65.62,
        "commentWeight": 47.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "package": "App\\Exceptions\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\AdminController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "daftartugas",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "confirmtugas",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rejecttugas",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "daftarket",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "confirmket",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rejectket",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Surat",
            "App\\Surat",
            "App\\Surat",
            "App\\Surat",
            "App\\SuratKet",
            "App\\SuratKet",
            "App\\SuratKet"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 7,
        "length": 76,
        "vocabulary": 15,
        "volume": 296.92,
        "difficulty": 6.5,
        "effort": 1930,
        "level": 0.15,
        "bugs": 0.1,
        "time": 107,
        "intelligentContent": 45.68,
        "number_operators": 24,
        "number_operands": 52,
        "number_operators_unique": 3,
        "number_operands_unique": 12,
        "cloc": 2,
        "loc": 53,
        "lloc": 51,
        "mi": 60.12,
        "mIwoC": 45.3,
        "commentWeight": 14.82,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.93,
        "relativeSystemComplexity": 10.93,
        "totalStructuralComplexity": 63,
        "totalDataComplexity": 13.5,
        "totalSystemComplexity": 76.5,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\ConfirmPasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 20,
        "loc": 30,
        "lloc": 10,
        "mi": 123.62,
        "mIwoC": 75.94,
        "commentWeight": 47.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\ForgotPasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 10,
        "loc": 15,
        "lloc": 5,
        "mi": 218.68,
        "mIwoC": 171,
        "commentWeight": 47.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\LoginController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 20,
        "loc": 30,
        "lloc": 10,
        "mi": 120.99,
        "mIwoC": 73.31,
        "commentWeight": 47.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\RegisterController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validator",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Validator",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\User"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 3,
        "length": 38,
        "vocabulary": 14,
        "volume": 144.68,
        "difficulty": 1.38,
        "effort": 200.33,
        "level": 0.72,
        "bugs": 0.05,
        "time": 11,
        "intelligentContent": 104.49,
        "number_operators": 2,
        "number_operands": 36,
        "number_operators_unique": 1,
        "number_operands_unique": 13,
        "cloc": 32,
        "loc": 50,
        "lloc": 18,
        "mi": 104.63,
        "mIwoC": 57.36,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 16.53,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1.6,
        "totalSystemComplexity": 49.6,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\ResetPasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 15,
        "loc": 21,
        "lloc": 6,
        "mi": 219.3,
        "mIwoC": 171,
        "commentWeight": 48.3,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\VerificationController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 0,
        "effort": 0,
        "level": 1.33,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 6,
        "cloc": 20,
        "loc": 32,
        "lloc": 12,
        "mi": 113.79,
        "mIwoC": 66.76,
        "commentWeight": 47.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Routing\\Controller"
        ],
        "parents": [
            "Illuminate\\Routing\\Controller"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.34,
        "afferentCoupling": 10,
        "efferentCoupling": 1,
        "instability": 0.09,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mahasiswaHome",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 3,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0.5,
        "effort": 6.97,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 27.86,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 10,
        "loc": 26,
        "lloc": 16,
        "mi": 106.57,
        "mIwoC": 65.59,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 6,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\SuratController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "daftarsrt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dashboardsrt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "tambah",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "simpan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hapus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "template",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\surat",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\surat",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\surat",
            "App\\surat",
            "App\\surat",
            "Illuminate\\Http\\Request",
            "App\\surat",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\surat"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 9,
        "length": 101,
        "vocabulary": 22,
        "volume": 450.4,
        "difficulty": 3.85,
        "effort": 1734.05,
        "level": 0.26,
        "bugs": 0.15,
        "time": 96,
        "intelligentContent": 116.99,
        "number_operators": 24,
        "number_operands": 77,
        "number_operators_unique": 2,
        "number_operands_unique": 20,
        "cloc": 2,
        "loc": 59,
        "lloc": 57,
        "mi": 57.05,
        "mIwoC": 42.98,
        "commentWeight": 14.07,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.61,
        "relativeSystemComplexity": 26.61,
        "totalStructuralComplexity": 225,
        "totalDataComplexity": 14.5,
        "totalSystemComplexity": 239.5,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\SuratKetController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "daftarsrt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dashboardsrt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "tambah",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "simpan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hapus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "template",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\SuratKet",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\SuratKet",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\SuratKet",
            "App\\SuratKet",
            "App\\SuratKet",
            "Illuminate\\Http\\Request",
            "App\\SuratKet",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\SuratKet"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 9,
        "length": 103,
        "vocabulary": 20,
        "volume": 445.16,
        "difficulty": 4.39,
        "effort": 1953.75,
        "level": 0.23,
        "bugs": 0.15,
        "time": 109,
        "intelligentContent": 101.43,
        "number_operators": 24,
        "number_operands": 79,
        "number_operators_unique": 2,
        "number_operands_unique": 18,
        "cloc": 2,
        "loc": 59,
        "lloc": 57,
        "mi": 57.09,
        "mIwoC": 43.02,
        "commentWeight": 14.07,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.61,
        "relativeSystemComplexity": 26.61,
        "totalStructuralComplexity": 225,
        "totalDataComplexity": 14.5,
        "totalSystemComplexity": 239.5,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Kernel"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Kernel"
        ],
        "lcom": 0,
        "length": 15,
        "vocabulary": 15,
        "volume": 58.6,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 117.21,
        "number_operators": 0,
        "number_operands": 15,
        "number_operators_unique": 0,
        "number_operands_unique": 15,
        "cloc": 20,
        "loc": 34,
        "lloc": 14,
        "mi": 108.87,
        "mIwoC": 62.49,
        "commentWeight": 46.38,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\Authenticate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "redirectTo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Auth\\Middleware\\Authenticate"
        ],
        "parents": [
            "Illuminate\\Auth\\Middleware\\Authenticate"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 1.5,
        "effort": 15,
        "level": 0.67,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6.67,
        "number_operators": 2,
        "number_operands": 3,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 6,
        "loc": 16,
        "lloc": 10,
        "mi": 111.55,
        "mIwoC": 70.92,
        "commentWeight": 40.63,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\CheckForMaintenanceMode",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\CheckRole",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Closure",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [],
        "lcom": 1,
        "length": 18,
        "vocabulary": 11,
        "volume": 62.27,
        "difficulty": 3.43,
        "effort": 213.5,
        "level": 0.29,
        "bugs": 0.02,
        "time": 12,
        "intelligentContent": 18.16,
        "number_operators": 6,
        "number_operands": 12,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 7,
        "loc": 22,
        "lloc": 15,
        "mi": 99.72,
        "mIwoC": 61.38,
        "commentWeight": 38.34,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 3,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\EncryptCookies",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Cookie\\Middleware\\EncryptCookies"
        ],
        "parents": [
            "Illuminate\\Cookie\\Middleware\\EncryptCookies"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\RedirectIfAuthenticated",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Closure",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 2,
        "effort": 41.79,
        "level": 0.5,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 10.45,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 8,
        "loc": 19,
        "lloc": 11,
        "mi": 109.99,
        "mIwoC": 67.77,
        "commentWeight": 42.21,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.67,
        "totalSystemComplexity": 5.67,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\Role",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Closure"
        ],
        "parents": [],
        "lcom": 1,
        "length": 11,
        "vocabulary": 8,
        "volume": 33,
        "difficulty": 2.1,
        "effort": 69.3,
        "level": 0.48,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 15.71,
        "number_operators": 4,
        "number_operands": 7,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 7,
        "loc": 18,
        "lloc": 11,
        "mi": 107.51,
        "mIwoC": 66.38,
        "commentWeight": 41.13,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 5.33,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\TrimStrings",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings"
        ],
        "lcom": 0,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 126.97,
        "mIwoC": 82.51,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\TrustProxies",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Fideloper\\Proxy\\TrustProxies"
        ],
        "parents": [
            "Fideloper\\Proxy\\TrustProxies"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 10,
        "loc": 16,
        "lloc": 6,
        "mi": 218.04,
        "mIwoC": 171,
        "commentWeight": 47.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\VerifyCsrfToken",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AppServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "lcom": 2,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 12,
        "loc": 22,
        "lloc": 10,
        "mi": 216.52,
        "mIwoC": 171,
        "commentWeight": 45.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AuthServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\AuthServiceProvider"
        ],
        "parents": [
            "Illuminate\\Foundation\\Support\\Providers\\AuthServiceProvider"
        ],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 11,
        "loc": 20,
        "lloc": 9,
        "mi": 216.62,
        "mIwoC": 171,
        "commentWeight": 45.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\BroadcastServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider",
            "Illuminate\\Support\\Facades\\Broadcast"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 210.96,
        "mIwoC": 171,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\EventServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\EventServiceProvider"
        ],
        "parents": [
            "Illuminate\\Foundation\\Support\\Providers\\EventServiceProvider"
        ],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 11,
        "loc": 20,
        "lloc": 9,
        "mi": 216.62,
        "mIwoC": 171,
        "commentWeight": 45.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\RouteServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "map",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mapWebRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mapApiRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider",
            "Illuminate\\Support\\Facades\\Route",
            "Illuminate\\Support\\Facades\\Route"
        ],
        "parents": [
            "Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider"
        ],
        "lcom": 2,
        "length": 11,
        "vocabulary": 7,
        "volume": 30.88,
        "difficulty": 0,
        "effort": 0,
        "level": 1.27,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 11,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 38,
        "loc": 61,
        "lloc": 23,
        "mi": 106.73,
        "mIwoC": 59.73,
        "commentWeight": 47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 49,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 196,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Surat",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 0,
        "length": 9,
        "vocabulary": 9,
        "volume": 28.53,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 6,
        "lloc": 6,
        "mi": 72.7,
        "mIwoC": 72.7,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\SuratKet",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 0,
        "length": 7,
        "vocabulary": 7,
        "volume": 19.65,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 7,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 6,
        "lloc": 6,
        "mi": 73.83,
        "mIwoC": 73.83,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\",
        "pageRank": 0.06,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "parents": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "lcom": 0,
        "length": 8,
        "vocabulary": 7,
        "volume": 22.46,
        "difficulty": 0,
        "effort": 0,
        "level": 1.75,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 8,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 15,
        "loc": 23,
        "lloc": 8,
        "mi": 118.17,
        "mIwoC": 70.7,
        "commentWeight": 47.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "CreateUsersTable",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 20,
        "vocabulary": 10,
        "volume": 66.44,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 66.44,
        "number_operators": 0,
        "number_operands": 20,
        "number_operators_unique": 0,
        "number_operands_unique": 10,
        "cloc": 10,
        "loc": 31,
        "lloc": 21,
        "mi": 96.8,
        "mIwoC": 58.26,
        "commentWeight": 38.53,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 100,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 200,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreatePasswordResetsTable",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 0,
        "effort": 0,
        "level": 1.11,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 10,
        "loc": 26,
        "lloc": 16,
        "mi": 105.34,
        "mIwoC": 64.36,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 50,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateFailedJobsTable",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 14,
        "vocabulary": 7,
        "volume": 39.3,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 14,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 10,
        "loc": 29,
        "lloc": 19,
        "mi": 100.27,
        "mIwoC": 60.81,
        "commentWeight": 39.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 72,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateSuratTable",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 12,
        "vocabulary": 6,
        "volume": 31.02,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 0,
        "number_operands": 12,
        "number_operators_unique": 0,
        "number_operands_unique": 6,
        "cloc": 10,
        "loc": 28,
        "lloc": 18,
        "mi": 101.99,
        "mIwoC": 62.04,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 50,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateInputSurat",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 15,
        "volume": 117.21,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.04,
        "time": 0,
        "intelligentContent": 117.21,
        "number_operators": 0,
        "number_operands": 30,
        "number_operators_unique": 0,
        "number_operands_unique": 15,
        "cloc": 10,
        "loc": 37,
        "lloc": 27,
        "mi": 90.21,
        "mIwoC": 54.15,
        "commentWeight": 36.05,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 72,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateSuratKeterangan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 24,
        "vocabulary": 12,
        "volume": 86.04,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.03,
        "time": 0,
        "intelligentContent": 86.04,
        "number_operators": 0,
        "number_operands": 24,
        "number_operators_unique": 0,
        "number_operands_unique": 12,
        "cloc": 10,
        "loc": 34,
        "lloc": 24,
        "mi": 93.45,
        "mIwoC": 56.21,
        "commentWeight": 37.24,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 72,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateSuratBeritaAcra",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 15,
        "volume": 117.21,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.04,
        "time": 0,
        "intelligentContent": 117.21,
        "number_operators": 0,
        "number_operands": 30,
        "number_operators_unique": 0,
        "number_operands_unique": 15,
        "cloc": 10,
        "loc": 37,
        "lloc": 27,
        "mi": 90.21,
        "mIwoC": 54.15,
        "commentWeight": 36.05,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 72,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateSuratKeputusan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 5,
        "vocabulary": 2,
        "volume": 5,
        "difficulty": 0,
        "effort": 0,
        "level": 0.8,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 10,
        "loc": 25,
        "lloc": 15,
        "mi": 110.84,
        "mIwoC": 69.32,
        "commentWeight": 41.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 9,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 18,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "DatabaseSeeder",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Seeder"
        ],
        "parents": [
            "Illuminate\\Database\\Seeder"
        ],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 6,
        "loc": 13,
        "lloc": 7,
        "mi": 214.43,
        "mIwoC": 171,
        "commentWeight": 43.43,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]